Update typo in brewfile
postgres spelled wrong

Assuming it should be postgres

```
Warning: 'postgress' formula is unreadable: No available formula with the name "postgress".
Error: No similarly named formulae found.
Error: No available formula with the name "postgress".
==> Searching for similarly named formulae...
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
Installing postgress has failed!
```